### ISSUE TITLE
Communter rails

### ISSUE THREAD

**Issue by abetusk** [abetusk/bostontraintrack#11]
Add real time commuter rail information.

Reference:
- [MBTA Real-Time Commuter Rail Data](http://www.mbta.com/rider_tools/developers/default.asp?id=21899)

**Comment by Friss** [comment]
Shouldn't be too hard to add in seems like a straight forward parse compared to the buses and at least this time it comes in JSON.

**Comment by abetusk** [comment]
Agreed.  I think having a separate server, like the bus server, is the best way to go.  It looks like there are 12 commuter lines, so I would suggest polling each one serially at 10 second intervals (so 120 seconds to make a complete loop).

I'm thinking of using the [Train Icon](http://mapicons.nicolasmollet.com/markers/transportation/other-types-of-transportation/train/) (from [Google Map Icons](http://mapicons.nicolasmollet.com/)) with the usual direction indicators.

I'll dive into making the icons.  If you want to make the server, let me know and I'll assign you.  Otherwise I'll work on it.

**Comment by abetusk** [comment]
I've made an initial [commuter rail server](https://github.com/abetusk/bostontraintrack/blob/master/srv/srv_commuter.js) which still needs some testing.

I've also made another toggle button to enable the commuter rails and the appropriate commuter rail icons.  The toggle button still isn't hooked up yet and the [bostontriantrack.js](https://github.com/abetusk/bostontraintrack/blob/master/www/js/bostontraintrack.js) hasn't been updated to receive commuter rail information.
