### ISSUE TITLE
Green line Stops

### ISSUE THREAD

**Issue by Friss** [abetusk/bostontraintrack#13]
I think we should display the Green line stop markers so if someone wanted to at least know if they are nearing a station it will be visible. What do you think @abetusk ?

**Comment by abetusk** [comment]
One concern is the visual clutter.  Another is that if the green stops are displayed, there will be an expectation that there should be metro markers for the green line.  The Thunderfoot tiling already has the stops there, so there is already an indication of when people are near stations.

I don't have strong opinions on the matter.  If you want them, we can put them in.

**Comment by Friss** [comment]
That makes sense only reason I brought it up was when I was moving files around I saw you had al the data on the green line so was curious if we should use it.

**Comment by abetusk** [comment]
Wishful thinking that there might be real time GPS data for the green line.  I'm going to close this issue.  If you have a change of heart, let me know.
