### ISSUE TITLE
Set initial map location based on GPS location of user

### ISSUE THREAD

**Issue by abetusk** [abetusk/bostontraintrack#7]
If the user has geolocation enabled, then the initial location of the map should be set to the users GPS location.  Care needs to be taken as it would be annoying to have a popup ask for location every time a new user visits the page.  It would be better to detect if the geolocation is active and use it if it is, otherwise allow the user to activate it explicitly via a button.

References:
  [Using Geolocation](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation)
  [OpenLayers Geolocation Example](http://openlayers.org/dev/examples/geolocation.html)

**Comment by Friss** [comment]
Do you think there should be a marker icon for the user's current position or just center the map on the user's position?

**Comment by abetusk** [comment]
My opinion is to just center the map and not have a marker.
